/*
onpremless

onpremless api

API version: 1.0.1
Contact: ilya.sumb@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opless

import (
	"encoding/json"
)

// checks if the BaseEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseEndpoint{}

// BaseEndpoint struct for BaseEndpoint
type BaseEndpoint struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Lambda string `json:"lambda"`
}

// NewBaseEndpoint instantiates a new BaseEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseEndpoint(name string, path string, lambda string) *BaseEndpoint {
	this := BaseEndpoint{}
	this.Name = name
	this.Path = path
	this.Lambda = lambda
	return &this
}

// NewBaseEndpointWithDefaults instantiates a new BaseEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseEndpointWithDefaults() *BaseEndpoint {
	this := BaseEndpoint{}
	return &this
}

// GetName returns the Name field value
func (o *BaseEndpoint) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BaseEndpoint) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BaseEndpoint) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *BaseEndpoint) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *BaseEndpoint) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *BaseEndpoint) SetPath(v string) {
	o.Path = v
}

// GetLambda returns the Lambda field value
func (o *BaseEndpoint) GetLambda() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lambda
}

// GetLambdaOk returns a tuple with the Lambda field value
// and a boolean to check if the value has been set.
func (o *BaseEndpoint) GetLambdaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lambda, true
}

// SetLambda sets field value
func (o *BaseEndpoint) SetLambda(v string) {
	o.Lambda = v
}

func (o BaseEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	toSerialize["lambda"] = o.Lambda
	return toSerialize, nil
}

type NullableBaseEndpoint struct {
	value *BaseEndpoint
	isSet bool
}

func (v NullableBaseEndpoint) Get() *BaseEndpoint {
	return v.value
}

func (v *NullableBaseEndpoint) Set(val *BaseEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseEndpoint(val *BaseEndpoint) *NullableBaseEndpoint {
	return &NullableBaseEndpoint{value: val, isSet: true}
}

func (v NullableBaseEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


