/*
onpremless

onpremless api

API version: 1.0.2
Contact: ilya.sumb@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opless

import (
	"encoding/json"
)

// checks if the CreateEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEndpoint{}

// CreateEndpoint struct for CreateEndpoint
type CreateEndpoint struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Lambda string `json:"lambda"`
}

// NewCreateEndpoint instantiates a new CreateEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEndpoint(name string, path string, lambda string) *CreateEndpoint {
	this := CreateEndpoint{}
	this.Name = name
	this.Path = path
	this.Lambda = lambda
	return &this
}

// NewCreateEndpointWithDefaults instantiates a new CreateEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEndpointWithDefaults() *CreateEndpoint {
	this := CreateEndpoint{}
	return &this
}

// GetName returns the Name field value
func (o *CreateEndpoint) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEndpoint) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEndpoint) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *CreateEndpoint) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *CreateEndpoint) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *CreateEndpoint) SetPath(v string) {
	o.Path = v
}

// GetLambda returns the Lambda field value
func (o *CreateEndpoint) GetLambda() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lambda
}

// GetLambdaOk returns a tuple with the Lambda field value
// and a boolean to check if the value has been set.
func (o *CreateEndpoint) GetLambdaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lambda, true
}

// SetLambda sets field value
func (o *CreateEndpoint) SetLambda(v string) {
	o.Lambda = v
}

func (o CreateEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	toSerialize["lambda"] = o.Lambda
	return toSerialize, nil
}

type NullableCreateEndpoint struct {
	value *CreateEndpoint
	isSet bool
}

func (v NullableCreateEndpoint) Get() *CreateEndpoint {
	return v.value
}

func (v *NullableCreateEndpoint) Set(val *CreateEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEndpoint(val *CreateEndpoint) *NullableCreateEndpoint {
	return &NullableCreateEndpoint{value: val, isSet: true}
}

func (v NullableCreateEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


